name: first workflow
on: push
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: print greetings
        run: echo "Hello Good Morning...!!!"
      - name: second message
        run: echo "Hii Good Bye...!!!"
